dev:
	docker compose up --build

down:
	docker compose down

clear-down:
	docker compose down -v

test:
	cd services/api-gateway && go test ./...
	cd services/auth-service && go test ./...
	cd services/profile-service && go test ./...
	cd services/listing-service && go test ./...
	cd services/application-service && go test ./...

lint:
	cd services/api-gateway && golangci-lint run ./...
	cd services/auth-service && golangci-lint run ./...
	cd services/profile-service && golangci-lint run ./...
	cd services/listing-service && golangci-lint run ./...
	cd services/application-service && golangci-lint run ./...