// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/profile/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ResumeUrl     string                 `protobuf:"bytes,9,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,10,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	LinkedinUrl   string                 `protobuf:"bytes,11,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	PortfolioUrl  string                 `protobuf:"bytes,12,opt,name=portfolio_url,json=portfolioUrl,proto3" json:"portfolio_url,omitempty"`
	Educations    []*EducationResponse   `protobuf:"bytes,13,rep,name=educations,proto3" json:"educations,omitempty"`
	Experiences   []*ExperienceResponse  `protobuf:"bytes,14,rep,name=experiences,proto3" json:"experiences,omitempty"`
	Projects      []*ProjectResponse     `protobuf:"bytes,15,rep,name=projects,proto3" json:"projects,omitempty"`
	Skills        []*SkillResponse       `protobuf:"bytes,16,rep,name=skills,proto3" json:"skills,omitempty"`
	Languages     []*LanguageResponse    `protobuf:"bytes,17,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentProfileResponse) Reset() {
	*x = StudentProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentProfileResponse) ProtoMessage() {}

func (x *StudentProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentProfileResponse.ProtoReflect.Descriptor instead.
func (*StudentProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *StudentProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudentProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StudentProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *StudentProfileResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *StudentProfileResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StudentProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *StudentProfileResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *StudentProfileResponse) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

func (x *StudentProfileResponse) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *StudentProfileResponse) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *StudentProfileResponse) GetPortfolioUrl() string {
	if x != nil {
		return x.PortfolioUrl
	}
	return ""
}

func (x *StudentProfileResponse) GetEducations() []*EducationResponse {
	if x != nil {
		return x.Educations
	}
	return nil
}

func (x *StudentProfileResponse) GetExperiences() []*ExperienceResponse {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *StudentProfileResponse) GetProjects() []*ProjectResponse {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *StudentProfileResponse) GetSkills() []*SkillResponse {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *StudentProfileResponse) GetLanguages() []*LanguageResponse {
	if x != nil {
		return x.Languages
	}
	return nil
}

type EducationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId      string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	University     string                 `protobuf:"bytes,3,opt,name=university,proto3" json:"university,omitempty"`
	Faculty        string                 `protobuf:"bytes,4,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Specialization string                 `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Degree         string                 `protobuf:"bytes,6,opt,name=degree,proto3" json:"degree,omitempty"`
	StartYear      int32                  `protobuf:"varint,7,opt,name=start_year,json=startYear,proto3" json:"start_year,omitempty"`
	EndYear        int32                  `protobuf:"varint,8,opt,name=end_year,json=endYear,proto3" json:"end_year,omitempty"`
	Gpa            float64                `protobuf:"fixed64,9,opt,name=gpa,proto3" json:"gpa,omitempty"`
	IsCurrent      bool                   `protobuf:"varint,10,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EducationResponse) Reset() {
	*x = EducationResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EducationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EducationResponse) ProtoMessage() {}

func (x *EducationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EducationResponse.ProtoReflect.Descriptor instead.
func (*EducationResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *EducationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EducationResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EducationResponse) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *EducationResponse) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *EducationResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *EducationResponse) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *EducationResponse) GetStartYear() int32 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *EducationResponse) GetEndYear() int32 {
	if x != nil {
		return x.EndYear
	}
	return 0
}

func (x *EducationResponse) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *EducationResponse) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type ExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,8,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceResponse) Reset() {
	*x = ExperienceResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceResponse) ProtoMessage() {}

func (x *ExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceResponse.ProtoReflect.Descriptor instead.
func (*ExperienceResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ExperienceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExperienceResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ExperienceResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ExperienceResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ExperienceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExperienceResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExperienceResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExperienceResponse) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *ExperienceResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Techs         []string               `protobuf:"bytes,6,rep,name=techs,proto3" json:"techs,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ProjectResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProjectResponse) GetTechs() []string {
	if x != nil {
		return x.Techs
	}
	return nil
}

func (x *ProjectResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ProjectResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type SkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Skill         string                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillResponse) Reset() {
	*x = SkillResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillResponse) ProtoMessage() {}

func (x *SkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillResponse.ProtoReflect.Descriptor instead.
func (*SkillResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *SkillResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *SkillResponse) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *SkillResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type LanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageResponse) Reset() {
	*x = LanguageResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageResponse) ProtoMessage() {}

func (x *LanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageResponse.ProtoReflect.Descriptor instead.
func (*LanguageResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *LanguageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LanguageResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LanguageResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LanguageResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type CompanyProfileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tagline          string                 `protobuf:"bytes,4,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Industry         string                 `protobuf:"bytes,6,opt,name=industry,proto3" json:"industry,omitempty"`
	Size             string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	FoundedYear      int32                  `protobuf:"varint,8,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	Website          string                 `protobuf:"bytes,9,opt,name=website,proto3" json:"website,omitempty"`
	ContactEmail     string                 `protobuf:"bytes,10,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	City             string                 `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Country          string                 `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"`
	IsRemoteFriendly bool                   `protobuf:"varint,13,opt,name=is_remote_friendly,json=isRemoteFriendly,proto3" json:"is_remote_friendly,omitempty"`
	LogoUrl          string                 `protobuf:"bytes,14,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompanyProfileResponse) Reset() {
	*x = CompanyProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyProfileResponse) ProtoMessage() {}

func (x *CompanyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyProfileResponse.ProtoReflect.Descriptor instead.
func (*CompanyProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *CompanyProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompanyProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyProfileResponse) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *CompanyProfileResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanyProfileResponse) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CompanyProfileResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CompanyProfileResponse) GetFoundedYear() int32 {
	if x != nil {
		return x.FoundedYear
	}
	return 0
}

func (x *CompanyProfileResponse) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CompanyProfileResponse) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *CompanyProfileResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CompanyProfileResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CompanyProfileResponse) GetIsRemoteFriendly() bool {
	if x != nil {
		return x.IsRemoteFriendly
	}
	return false
}

func (x *CompanyProfileResponse) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type GetMyStudentProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyStudentProfileRequest) Reset() {
	*x = GetMyStudentProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyStudentProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyStudentProfileRequest) ProtoMessage() {}

func (x *GetMyStudentProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyStudentProfileRequest.ProtoReflect.Descriptor instead.
func (*GetMyStudentProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{7}
}

func (x *GetMyStudentProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStudentProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentProfileRequest) Reset() {
	*x = GetStudentProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentProfileRequest) ProtoMessage() {}

func (x *GetStudentProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentProfileRequest.ProtoReflect.Descriptor instead.
func (*GetStudentProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{8}
}

func (x *GetStudentProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateStudentProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,7,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	LinkedinUrl   string                 `protobuf:"bytes,8,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	PortfolioUrl  string                 `protobuf:"bytes,9,opt,name=portfolio_url,json=portfolioUrl,proto3" json:"portfolio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentProfileRequest) Reset() {
	*x = UpdateStudentProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentProfileRequest) ProtoMessage() {}

func (x *UpdateStudentProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStudentProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *UpdateStudentProfileRequest) GetPortfolioUrl() string {
	if x != nil {
		return x.PortfolioUrl
	}
	return ""
}

type UploadAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{10}
}

func (x *UploadAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadAvatarRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{11}
}

func (x *UploadAvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UploadResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeRequest) Reset() {
	*x = UploadResumeRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeRequest) ProtoMessage() {}

func (x *UploadResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeRequest.ProtoReflect.Descriptor instead.
func (*UploadResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{12}
}

func (x *UploadResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadResumeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeUrl     string                 `protobuf:"bytes,1,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeResponse) Reset() {
	*x = UploadResumeResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeResponse) ProtoMessage() {}

func (x *UploadResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeResponse.ProtoReflect.Descriptor instead.
func (*UploadResumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{13}
}

func (x *UploadResumeResponse) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

type GetResumeURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeURLRequest) Reset() {
	*x = GetResumeURLRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeURLRequest) ProtoMessage() {}

func (x *GetResumeURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeURLRequest.ProtoReflect.Descriptor instead.
func (*GetResumeURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{14}
}

func (x *GetResumeURLRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetResumeURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeURLResponse) Reset() {
	*x = GetResumeURLResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeURLResponse) ProtoMessage() {}

func (x *GetResumeURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeURLResponse.ProtoReflect.Descriptor instead.
func (*GetResumeURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{15}
}

func (x *GetResumeURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddEducationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	University     string                 `protobuf:"bytes,2,opt,name=university,proto3" json:"university,omitempty"`
	Faculty        string                 `protobuf:"bytes,3,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Specialization string                 `protobuf:"bytes,4,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Degree         string                 `protobuf:"bytes,5,opt,name=degree,proto3" json:"degree,omitempty"`
	StartYear      int32                  `protobuf:"varint,6,opt,name=start_year,json=startYear,proto3" json:"start_year,omitempty"`
	EndYear        int32                  `protobuf:"varint,7,opt,name=end_year,json=endYear,proto3" json:"end_year,omitempty"`
	Gpa            float64                `protobuf:"fixed64,8,opt,name=gpa,proto3" json:"gpa,omitempty"`
	IsCurrent      bool                   `protobuf:"varint,9,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddEducationRequest) Reset() {
	*x = AddEducationRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEducationRequest) ProtoMessage() {}

func (x *AddEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEducationRequest.ProtoReflect.Descriptor instead.
func (*AddEducationRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{16}
}

func (x *AddEducationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddEducationRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *AddEducationRequest) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *AddEducationRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *AddEducationRequest) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *AddEducationRequest) GetStartYear() int32 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *AddEducationRequest) GetEndYear() int32 {
	if x != nil {
		return x.EndYear
	}
	return 0
}

func (x *AddEducationRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *AddEducationRequest) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type UpdateEducationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	University     string                 `protobuf:"bytes,3,opt,name=university,proto3" json:"university,omitempty"`
	Faculty        string                 `protobuf:"bytes,4,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Specialization string                 `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Degree         string                 `protobuf:"bytes,6,opt,name=degree,proto3" json:"degree,omitempty"`
	StartYear      int32                  `protobuf:"varint,7,opt,name=start_year,json=startYear,proto3" json:"start_year,omitempty"`
	EndYear        int32                  `protobuf:"varint,8,opt,name=end_year,json=endYear,proto3" json:"end_year,omitempty"`
	Gpa            float64                `protobuf:"fixed64,9,opt,name=gpa,proto3" json:"gpa,omitempty"`
	IsCurrent      bool                   `protobuf:"varint,10,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEducationRequest) Reset() {
	*x = UpdateEducationRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEducationRequest) ProtoMessage() {}

func (x *UpdateEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEducationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEducationRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateEducationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEducationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEducationRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *UpdateEducationRequest) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *UpdateEducationRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *UpdateEducationRequest) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *UpdateEducationRequest) GetStartYear() int32 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *UpdateEducationRequest) GetEndYear() int32 {
	if x != nil {
		return x.EndYear
	}
	return 0
}

func (x *UpdateEducationRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *UpdateEducationRequest) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type DeleteEducationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEducationRequest) Reset() {
	*x = DeleteEducationRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEducationRequest) ProtoMessage() {}

func (x *DeleteEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEducationRequest.ProtoReflect.Descriptor instead.
func (*DeleteEducationRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteEducationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteEducationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,7,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	Format        string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExperienceRequest) Reset() {
	*x = AddExperienceRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExperienceRequest) ProtoMessage() {}

func (x *AddExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExperienceRequest.ProtoReflect.Descriptor instead.
func (*AddExperienceRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{19}
}

func (x *AddExperienceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddExperienceRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *AddExperienceRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *AddExperienceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddExperienceRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AddExperienceRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AddExperienceRequest) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *AddExperienceRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type UpdateExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,8,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExperienceRequest) Reset() {
	*x = UpdateExperienceRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExperienceRequest) ProtoMessage() {}

func (x *UpdateExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExperienceRequest.ProtoReflect.Descriptor instead.
func (*UpdateExperienceRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExperienceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateExperienceRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *UpdateExperienceRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateExperienceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExperienceRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateExperienceRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateExperienceRequest) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *UpdateExperienceRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type DeleteExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExperienceRequest) Reset() {
	*x = DeleteExperienceRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExperienceRequest) ProtoMessage() {}

func (x *DeleteExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExperienceRequest.ProtoReflect.Descriptor instead.
func (*DeleteExperienceRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteExperienceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Techs         []string               `protobuf:"bytes,5,rep,name=techs,proto3" json:"techs,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectRequest) Reset() {
	*x = AddProjectRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectRequest) ProtoMessage() {}

func (x *AddProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectRequest.ProtoReflect.Descriptor instead.
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{22}
}

func (x *AddProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProjectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddProjectRequest) GetTechs() []string {
	if x != nil {
		return x.Techs
	}
	return nil
}

func (x *AddProjectRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AddProjectRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Techs         []string               `protobuf:"bytes,6,rep,name=techs,proto3" json:"techs,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateProjectRequest) GetTechs() []string {
	if x != nil {
		return x.Techs
	}
	return nil
}

func (x *UpdateProjectRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateProjectRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMyCompanyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyCompanyProfileRequest) Reset() {
	*x = GetMyCompanyProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyCompanyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyCompanyProfileRequest) ProtoMessage() {}

func (x *GetMyCompanyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyCompanyProfileRequest.ProtoReflect.Descriptor instead.
func (*GetMyCompanyProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{26}
}

func (x *GetMyCompanyProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCompanyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyProfileRequest) Reset() {
	*x = GetCompanyProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyProfileRequest) ProtoMessage() {}

func (x *GetCompanyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{27}
}

func (x *GetCompanyProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCompanyProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tagline          string                 `protobuf:"bytes,3,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Industry         string                 `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	Size             string                 `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	FoundedYear      int32                  `protobuf:"varint,7,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	Website          string                 `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	ContactEmail     string                 `protobuf:"bytes,9,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	City             string                 `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Country          string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	IsRemoteFriendly bool                   `protobuf:"varint,12,opt,name=is_remote_friendly,json=isRemoteFriendly,proto3" json:"is_remote_friendly,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCompanyProfileRequest) Reset() {
	*x = UpdateCompanyProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyProfileRequest) ProtoMessage() {}

func (x *UpdateCompanyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateCompanyProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetFoundedYear() int32 {
	if x != nil {
		return x.FoundedYear
	}
	return 0
}

func (x *UpdateCompanyProfileRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateCompanyProfileRequest) GetIsRemoteFriendly() bool {
	if x != nil {
		return x.IsRemoteFriendly
	}
	return false
}

type UploadLogoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogoRequest) Reset() {
	*x = UploadLogoRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogoRequest) ProtoMessage() {}

func (x *UploadLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogoRequest.ProtoReflect.Descriptor instead.
func (*UploadLogoRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{29}
}

func (x *UploadLogoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadLogoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadLogoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadLogoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUrl       string                 `protobuf:"bytes,1,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogoResponse) Reset() {
	*x = UploadLogoResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogoResponse) ProtoMessage() {}

func (x *UploadLogoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogoResponse.ProtoReflect.Descriptor instead.
func (*UploadLogoResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{30}
}

func (x *UploadLogoResponse) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

var File_proto_profile_profile_proto protoreflect.FileDescriptor

const file_proto_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/profile/profile.proto\x12\aprofile\"\xf8\x04\n" +
	"\x16StudentProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"resume_url\x18\t \x01(\tR\tresumeUrl\x12\x1d\n" +
	"\n" +
	"github_url\x18\n" +
	" \x01(\tR\tgithubUrl\x12!\n" +
	"\flinkedin_url\x18\v \x01(\tR\vlinkedinUrl\x12#\n" +
	"\rportfolio_url\x18\f \x01(\tR\fportfolioUrl\x12:\n" +
	"\n" +
	"educations\x18\r \x03(\v2\x1a.profile.EducationResponseR\n" +
	"educations\x12=\n" +
	"\vexperiences\x18\x0e \x03(\v2\x1b.profile.ExperienceResponseR\vexperiences\x124\n" +
	"\bprojects\x18\x0f \x03(\v2\x18.profile.ProjectResponseR\bprojects\x12.\n" +
	"\x06skills\x18\x10 \x03(\v2\x16.profile.SkillResponseR\x06skills\x127\n" +
	"\tlanguages\x18\x11 \x03(\v2\x19.profile.LanguageResponseR\tlanguages\"\xa7\x02\n" +
	"\x11EducationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1e\n" +
	"\n" +
	"university\x18\x03 \x01(\tR\n" +
	"university\x12\x18\n" +
	"\afaculty\x18\x04 \x01(\tR\afaculty\x12&\n" +
	"\x0especialization\x18\x05 \x01(\tR\x0especialization\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\tR\x06degree\x12\x1d\n" +
	"\n" +
	"start_year\x18\a \x01(\x05R\tstartYear\x12\x19\n" +
	"\bend_year\x18\b \x01(\x05R\aendYear\x12\x10\n" +
	"\x03gpa\x18\t \x01(\x01R\x03gpa\x12\x1d\n" +
	"\n" +
	"is_current\x18\n" +
	" \x01(\bR\tisCurrent\"\x95\x02\n" +
	"\x12ExperienceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"is_current\x18\b \x01(\bR\tisCurrent\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\"\xda\x01\n" +
	"\x0fProjectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x14\n" +
	"\x05techs\x18\x06 \x03(\tR\x05techs\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\tR\aendDate\"j\n" +
	"\rSkillResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05skill\x18\x03 \x01(\tR\x05skill\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\"s\n" +
	"\x10LanguageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\"\x9a\x03\n" +
	"\x16CompanyProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\atagline\x18\x04 \x01(\tR\atagline\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bindustry\x18\x06 \x01(\tR\bindustry\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12!\n" +
	"\ffounded_year\x18\b \x01(\x05R\vfoundedYear\x12\x18\n" +
	"\awebsite\x18\t \x01(\tR\awebsite\x12#\n" +
	"\rcontact_email\x18\n" +
	" \x01(\tR\fcontactEmail\x12\x12\n" +
	"\x04city\x18\v \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\f \x01(\tR\acountry\x12,\n" +
	"\x12is_remote_friendly\x18\r \x01(\bR\x10isRemoteFriendly\x12\x19\n" +
	"\blogo_url\x18\x0e \x01(\tR\alogoUrl\"5\n" +
	"\x1aGetMyStudentProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x18GetStudentProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x02\n" +
	"\x1bUpdateStudentProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"github_url\x18\a \x01(\tR\tgithubUrl\x12!\n" +
	"\flinkedin_url\x18\b \x01(\tR\vlinkedinUrl\x12#\n" +
	"\rportfolio_url\x18\t \x01(\tR\fportfolioUrl\"e\n" +
	"\x13UploadAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"5\n" +
	"\x14UploadAvatarResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\"B\n" +
	"\x13UploadResumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"5\n" +
	"\x14UploadResumeResponse\x12\x1d\n" +
	"\n" +
	"resume_url\x18\x01 \x01(\tR\tresumeUrl\"4\n" +
	"\x13GetResumeURLRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"(\n" +
	"\x14GetResumeURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x93\x02\n" +
	"\x13AddEducationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"university\x18\x02 \x01(\tR\n" +
	"university\x12\x18\n" +
	"\afaculty\x18\x03 \x01(\tR\afaculty\x12&\n" +
	"\x0especialization\x18\x04 \x01(\tR\x0especialization\x12\x16\n" +
	"\x06degree\x18\x05 \x01(\tR\x06degree\x12\x1d\n" +
	"\n" +
	"start_year\x18\x06 \x01(\x05R\tstartYear\x12\x19\n" +
	"\bend_year\x18\a \x01(\x05R\aendYear\x12\x10\n" +
	"\x03gpa\x18\b \x01(\x01R\x03gpa\x12\x1d\n" +
	"\n" +
	"is_current\x18\t \x01(\bR\tisCurrent\"\xa6\x02\n" +
	"\x16UpdateEducationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"university\x18\x03 \x01(\tR\n" +
	"university\x12\x18\n" +
	"\afaculty\x18\x04 \x01(\tR\afaculty\x12&\n" +
	"\x0especialization\x18\x05 \x01(\tR\x0especialization\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\tR\x06degree\x12\x1d\n" +
	"\n" +
	"start_year\x18\a \x01(\x05R\tstartYear\x12\x19\n" +
	"\bend_year\x18\b \x01(\x05R\aendYear\x12\x10\n" +
	"\x03gpa\x18\t \x01(\x01R\x03gpa\x12\x1d\n" +
	"\n" +
	"is_current\x18\n" +
	" \x01(\bR\tisCurrent\"A\n" +
	"\x16DeleteEducationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x81\x02\n" +
	"\x14AddExperienceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"is_current\x18\a \x01(\bR\tisCurrent\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06format\"\x94\x02\n" +
	"\x17UpdateExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"is_current\x18\b \x01(\bR\tisCurrent\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\"B\n" +
	"\x17DeleteExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc6\x01\n" +
	"\x11AddProjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05techs\x18\x05 \x03(\tR\x05techs\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\"\xd9\x01\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x14\n" +
	"\x05techs\x18\x06 \x03(\tR\x05techs\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\tR\aendDate\"?\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aGetMyCompanyProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x18GetCompanyProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf4\x02\n" +
	"\x1bUpdateCompanyProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\atagline\x18\x03 \x01(\tR\atagline\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12\x12\n" +
	"\x04size\x18\x06 \x01(\tR\x04size\x12!\n" +
	"\ffounded_year\x18\a \x01(\x05R\vfoundedYear\x12\x18\n" +
	"\awebsite\x18\b \x01(\tR\awebsite\x12#\n" +
	"\rcontact_email\x18\t \x01(\tR\fcontactEmail\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12,\n" +
	"\x12is_remote_friendly\x18\f \x01(\bR\x10isRemoteFriendly\"c\n" +
	"\x11UploadLogoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"/\n" +
	"\x12UploadLogoResponse\x12\x19\n" +
	"\blogo_url\x18\x01 \x01(\tR\alogoUrl2\x95\f\n" +
	"\x0eProfileService\x12[\n" +
	"\x13GetMyStudentProfile\x12#.profile.GetMyStudentProfileRequest\x1a\x1f.profile.StudentProfileResponse\x12W\n" +
	"\x11GetStudentProfile\x12!.profile.GetStudentProfileRequest\x1a\x1f.profile.StudentProfileResponse\x12]\n" +
	"\x14UpdateStudentProfile\x12$.profile.UpdateStudentProfileRequest\x1a\x1f.profile.StudentProfileResponse\x12K\n" +
	"\fUploadAvatar\x12\x1c.profile.UploadAvatarRequest\x1a\x1d.profile.UploadAvatarResponse\x12K\n" +
	"\fUploadResume\x12\x1c.profile.UploadResumeRequest\x1a\x1d.profile.UploadResumeResponse\x12K\n" +
	"\fGetResumeURL\x12\x1c.profile.GetResumeURLRequest\x1a\x1d.profile.GetResumeURLResponse\x12H\n" +
	"\fAddEducation\x12\x1c.profile.AddEducationRequest\x1a\x1a.profile.EducationResponse\x12N\n" +
	"\x0fUpdateEducation\x12\x1f.profile.UpdateEducationRequest\x1a\x1a.profile.EducationResponse\x12K\n" +
	"\x0fDeleteEducation\x12\x1f.profile.DeleteEducationRequest\x1a\x17.profile.DeleteResponse\x12K\n" +
	"\rAddExperience\x12\x1d.profile.AddExperienceRequest\x1a\x1b.profile.ExperienceResponse\x12Q\n" +
	"\x10UpdateExperience\x12 .profile.UpdateExperienceRequest\x1a\x1b.profile.ExperienceResponse\x12M\n" +
	"\x10DeleteExperience\x12 .profile.DeleteExperienceRequest\x1a\x17.profile.DeleteResponse\x12B\n" +
	"\n" +
	"AddProject\x12\x1a.profile.AddProjectRequest\x1a\x18.profile.ProjectResponse\x12H\n" +
	"\rUpdateProject\x12\x1d.profile.UpdateProjectRequest\x1a\x18.profile.ProjectResponse\x12G\n" +
	"\rDeleteProject\x12\x1d.profile.DeleteProjectRequest\x1a\x17.profile.DeleteResponse\x12[\n" +
	"\x13GetMyCompanyProfile\x12#.profile.GetMyCompanyProfileRequest\x1a\x1f.profile.CompanyProfileResponse\x12W\n" +
	"\x11GetCompanyProfile\x12!.profile.GetCompanyProfileRequest\x1a\x1f.profile.CompanyProfileResponse\x12]\n" +
	"\x14UpdateCompanyProfile\x12$.profile.UpdateCompanyProfileRequest\x1a\x1f.profile.CompanyProfileResponse\x12E\n" +
	"\n" +
	"UploadLogo\x12\x1a.profile.UploadLogoRequest\x1a\x1b.profile.UploadLogoResponseB4Z2github.com/Kost0/internship-exchange/proto/profileb\x06proto3"

var (
	file_proto_profile_profile_proto_rawDescOnce sync.Once
	file_proto_profile_profile_proto_rawDescData []byte
)

func file_proto_profile_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)))
	})
	return file_proto_profile_profile_proto_rawDescData
}

var file_proto_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_profile_profile_proto_goTypes = []any{
	(*StudentProfileResponse)(nil),      // 0: profile.StudentProfileResponse
	(*EducationResponse)(nil),           // 1: profile.EducationResponse
	(*ExperienceResponse)(nil),          // 2: profile.ExperienceResponse
	(*ProjectResponse)(nil),             // 3: profile.ProjectResponse
	(*SkillResponse)(nil),               // 4: profile.SkillResponse
	(*LanguageResponse)(nil),            // 5: profile.LanguageResponse
	(*CompanyProfileResponse)(nil),      // 6: profile.CompanyProfileResponse
	(*GetMyStudentProfileRequest)(nil),  // 7: profile.GetMyStudentProfileRequest
	(*GetStudentProfileRequest)(nil),    // 8: profile.GetStudentProfileRequest
	(*UpdateStudentProfileRequest)(nil), // 9: profile.UpdateStudentProfileRequest
	(*UploadAvatarRequest)(nil),         // 10: profile.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),        // 11: profile.UploadAvatarResponse
	(*UploadResumeRequest)(nil),         // 12: profile.UploadResumeRequest
	(*UploadResumeResponse)(nil),        // 13: profile.UploadResumeResponse
	(*GetResumeURLRequest)(nil),         // 14: profile.GetResumeURLRequest
	(*GetResumeURLResponse)(nil),        // 15: profile.GetResumeURLResponse
	(*AddEducationRequest)(nil),         // 16: profile.AddEducationRequest
	(*UpdateEducationRequest)(nil),      // 17: profile.UpdateEducationRequest
	(*DeleteEducationRequest)(nil),      // 18: profile.DeleteEducationRequest
	(*AddExperienceRequest)(nil),        // 19: profile.AddExperienceRequest
	(*UpdateExperienceRequest)(nil),     // 20: profile.UpdateExperienceRequest
	(*DeleteExperienceRequest)(nil),     // 21: profile.DeleteExperienceRequest
	(*AddProjectRequest)(nil),           // 22: profile.AddProjectRequest
	(*UpdateProjectRequest)(nil),        // 23: profile.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),        // 24: profile.DeleteProjectRequest
	(*DeleteResponse)(nil),              // 25: profile.DeleteResponse
	(*GetMyCompanyProfileRequest)(nil),  // 26: profile.GetMyCompanyProfileRequest
	(*GetCompanyProfileRequest)(nil),    // 27: profile.GetCompanyProfileRequest
	(*UpdateCompanyProfileRequest)(nil), // 28: profile.UpdateCompanyProfileRequest
	(*UploadLogoRequest)(nil),           // 29: profile.UploadLogoRequest
	(*UploadLogoResponse)(nil),          // 30: profile.UploadLogoResponse
}
var file_proto_profile_profile_proto_depIdxs = []int32{
	1,  // 0: profile.StudentProfileResponse.educations:type_name -> profile.EducationResponse
	2,  // 1: profile.StudentProfileResponse.experiences:type_name -> profile.ExperienceResponse
	3,  // 2: profile.StudentProfileResponse.projects:type_name -> profile.ProjectResponse
	4,  // 3: profile.StudentProfileResponse.skills:type_name -> profile.SkillResponse
	5,  // 4: profile.StudentProfileResponse.languages:type_name -> profile.LanguageResponse
	7,  // 5: profile.ProfileService.GetMyStudentProfile:input_type -> profile.GetMyStudentProfileRequest
	8,  // 6: profile.ProfileService.GetStudentProfile:input_type -> profile.GetStudentProfileRequest
	9,  // 7: profile.ProfileService.UpdateStudentProfile:input_type -> profile.UpdateStudentProfileRequest
	10, // 8: profile.ProfileService.UploadAvatar:input_type -> profile.UploadAvatarRequest
	12, // 9: profile.ProfileService.UploadResume:input_type -> profile.UploadResumeRequest
	14, // 10: profile.ProfileService.GetResumeURL:input_type -> profile.GetResumeURLRequest
	16, // 11: profile.ProfileService.AddEducation:input_type -> profile.AddEducationRequest
	17, // 12: profile.ProfileService.UpdateEducation:input_type -> profile.UpdateEducationRequest
	18, // 13: profile.ProfileService.DeleteEducation:input_type -> profile.DeleteEducationRequest
	19, // 14: profile.ProfileService.AddExperience:input_type -> profile.AddExperienceRequest
	20, // 15: profile.ProfileService.UpdateExperience:input_type -> profile.UpdateExperienceRequest
	21, // 16: profile.ProfileService.DeleteExperience:input_type -> profile.DeleteExperienceRequest
	22, // 17: profile.ProfileService.AddProject:input_type -> profile.AddProjectRequest
	23, // 18: profile.ProfileService.UpdateProject:input_type -> profile.UpdateProjectRequest
	24, // 19: profile.ProfileService.DeleteProject:input_type -> profile.DeleteProjectRequest
	26, // 20: profile.ProfileService.GetMyCompanyProfile:input_type -> profile.GetMyCompanyProfileRequest
	27, // 21: profile.ProfileService.GetCompanyProfile:input_type -> profile.GetCompanyProfileRequest
	28, // 22: profile.ProfileService.UpdateCompanyProfile:input_type -> profile.UpdateCompanyProfileRequest
	29, // 23: profile.ProfileService.UploadLogo:input_type -> profile.UploadLogoRequest
	0,  // 24: profile.ProfileService.GetMyStudentProfile:output_type -> profile.StudentProfileResponse
	0,  // 25: profile.ProfileService.GetStudentProfile:output_type -> profile.StudentProfileResponse
	0,  // 26: profile.ProfileService.UpdateStudentProfile:output_type -> profile.StudentProfileResponse
	11, // 27: profile.ProfileService.UploadAvatar:output_type -> profile.UploadAvatarResponse
	13, // 28: profile.ProfileService.UploadResume:output_type -> profile.UploadResumeResponse
	15, // 29: profile.ProfileService.GetResumeURL:output_type -> profile.GetResumeURLResponse
	1,  // 30: profile.ProfileService.AddEducation:output_type -> profile.EducationResponse
	1,  // 31: profile.ProfileService.UpdateEducation:output_type -> profile.EducationResponse
	25, // 32: profile.ProfileService.DeleteEducation:output_type -> profile.DeleteResponse
	2,  // 33: profile.ProfileService.AddExperience:output_type -> profile.ExperienceResponse
	2,  // 34: profile.ProfileService.UpdateExperience:output_type -> profile.ExperienceResponse
	25, // 35: profile.ProfileService.DeleteExperience:output_type -> profile.DeleteResponse
	3,  // 36: profile.ProfileService.AddProject:output_type -> profile.ProjectResponse
	3,  // 37: profile.ProfileService.UpdateProject:output_type -> profile.ProjectResponse
	25, // 38: profile.ProfileService.DeleteProject:output_type -> profile.DeleteResponse
	6,  // 39: profile.ProfileService.GetMyCompanyProfile:output_type -> profile.CompanyProfileResponse
	6,  // 40: profile.ProfileService.GetCompanyProfile:output_type -> profile.CompanyProfileResponse
	6,  // 41: profile.ProfileService.UpdateCompanyProfile:output_type -> profile.CompanyProfileResponse
	30, // 42: profile.ProfileService.UploadLogo:output_type -> profile.UploadLogoResponse
	24, // [24:43] is the sub-list for method output_type
	5,  // [5:24] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_profile_profile_proto_init() }
func file_proto_profile_profile_proto_init() {
	if File_proto_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_profile_proto = out.File
	file_proto_profile_profile_proto_goTypes = nil
	file_proto_profile_profile_proto_depIdxs = nil
}
