// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/profile/profile.proto

package profile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_GetMyStudentProfile_FullMethodName  = "/profile.ProfileService/GetMyStudentProfile"
	ProfileService_GetStudentProfile_FullMethodName    = "/profile.ProfileService/GetStudentProfile"
	ProfileService_UpdateStudentProfile_FullMethodName = "/profile.ProfileService/UpdateStudentProfile"
	ProfileService_UploadAvatar_FullMethodName         = "/profile.ProfileService/UploadAvatar"
	ProfileService_UploadResume_FullMethodName         = "/profile.ProfileService/UploadResume"
	ProfileService_GetResumeURL_FullMethodName         = "/profile.ProfileService/GetResumeURL"
	ProfileService_AddEducation_FullMethodName         = "/profile.ProfileService/AddEducation"
	ProfileService_UpdateEducation_FullMethodName      = "/profile.ProfileService/UpdateEducation"
	ProfileService_DeleteEducation_FullMethodName      = "/profile.ProfileService/DeleteEducation"
	ProfileService_AddExperience_FullMethodName        = "/profile.ProfileService/AddExperience"
	ProfileService_UpdateExperience_FullMethodName     = "/profile.ProfileService/UpdateExperience"
	ProfileService_DeleteExperience_FullMethodName     = "/profile.ProfileService/DeleteExperience"
	ProfileService_AddProject_FullMethodName           = "/profile.ProfileService/AddProject"
	ProfileService_UpdateProject_FullMethodName        = "/profile.ProfileService/UpdateProject"
	ProfileService_DeleteProject_FullMethodName        = "/profile.ProfileService/DeleteProject"
	ProfileService_GetMyCompanyProfile_FullMethodName  = "/profile.ProfileService/GetMyCompanyProfile"
	ProfileService_GetCompanyProfile_FullMethodName    = "/profile.ProfileService/GetCompanyProfile"
	ProfileService_UpdateCompanyProfile_FullMethodName = "/profile.ProfileService/UpdateCompanyProfile"
	ProfileService_UploadLogo_FullMethodName           = "/profile.ProfileService/UploadLogo"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	GetMyStudentProfile(ctx context.Context, in *GetMyStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error)
	GetStudentProfile(ctx context.Context, in *GetStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error)
	UpdateStudentProfile(ctx context.Context, in *UpdateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error)
	UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error)
	UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*UploadResumeResponse, error)
	GetResumeURL(ctx context.Context, in *GetResumeURLRequest, opts ...grpc.CallOption) (*GetResumeURLResponse, error)
	AddEducation(ctx context.Context, in *AddEducationRequest, opts ...grpc.CallOption) (*EducationResponse, error)
	UpdateEducation(ctx context.Context, in *UpdateEducationRequest, opts ...grpc.CallOption) (*EducationResponse, error)
	DeleteEducation(ctx context.Context, in *DeleteEducationRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	AddExperience(ctx context.Context, in *AddExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error)
	UpdateExperience(ctx context.Context, in *UpdateExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error)
	DeleteExperience(ctx context.Context, in *DeleteExperienceRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetMyCompanyProfile(ctx context.Context, in *GetMyCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error)
	GetCompanyProfile(ctx context.Context, in *GetCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error)
	UpdateCompanyProfile(ctx context.Context, in *UpdateCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error)
	UploadLogo(ctx context.Context, in *UploadLogoRequest, opts ...grpc.CallOption) (*UploadLogoResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetMyStudentProfile(ctx context.Context, in *GetMyStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetMyStudentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetStudentProfile(ctx context.Context, in *GetStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetStudentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateStudentProfile(ctx context.Context, in *UpdateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateStudentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatarResponse)
	err := c.cc.Invoke(ctx, ProfileService_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*UploadResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResumeResponse)
	err := c.cc.Invoke(ctx, ProfileService_UploadResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetResumeURL(ctx context.Context, in *GetResumeURLRequest, opts ...grpc.CallOption) (*GetResumeURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResumeURLResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetResumeURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) AddEducation(ctx context.Context, in *AddEducationRequest, opts ...grpc.CallOption) (*EducationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EducationResponse)
	err := c.cc.Invoke(ctx, ProfileService_AddEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateEducation(ctx context.Context, in *UpdateEducationRequest, opts ...grpc.CallOption) (*EducationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EducationResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteEducation(ctx context.Context, in *DeleteEducationRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ProfileService_DeleteEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) AddExperience(ctx context.Context, in *AddExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperienceResponse)
	err := c.cc.Invoke(ctx, ProfileService_AddExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateExperience(ctx context.Context, in *UpdateExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperienceResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteExperience(ctx context.Context, in *DeleteExperienceRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ProfileService_DeleteExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ProfileService_AddProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ProfileService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetMyCompanyProfile(ctx context.Context, in *GetMyCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetMyCompanyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetCompanyProfile(ctx context.Context, in *GetCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetCompanyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateCompanyProfile(ctx context.Context, in *UpdateCompanyProfileRequest, opts ...grpc.CallOption) (*CompanyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_UpdateCompanyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UploadLogo(ctx context.Context, in *UploadLogoRequest, opts ...grpc.CallOption) (*UploadLogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadLogoResponse)
	err := c.cc.Invoke(ctx, ProfileService_UploadLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
type ProfileServiceServer interface {
	GetMyStudentProfile(context.Context, *GetMyStudentProfileRequest) (*StudentProfileResponse, error)
	GetStudentProfile(context.Context, *GetStudentProfileRequest) (*StudentProfileResponse, error)
	UpdateStudentProfile(context.Context, *UpdateStudentProfileRequest) (*StudentProfileResponse, error)
	UploadAvatar(context.Context, *UploadAvatarRequest) (*UploadAvatarResponse, error)
	UploadResume(context.Context, *UploadResumeRequest) (*UploadResumeResponse, error)
	GetResumeURL(context.Context, *GetResumeURLRequest) (*GetResumeURLResponse, error)
	AddEducation(context.Context, *AddEducationRequest) (*EducationResponse, error)
	UpdateEducation(context.Context, *UpdateEducationRequest) (*EducationResponse, error)
	DeleteEducation(context.Context, *DeleteEducationRequest) (*DeleteResponse, error)
	AddExperience(context.Context, *AddExperienceRequest) (*ExperienceResponse, error)
	UpdateExperience(context.Context, *UpdateExperienceRequest) (*ExperienceResponse, error)
	DeleteExperience(context.Context, *DeleteExperienceRequest) (*DeleteResponse, error)
	AddProject(context.Context, *AddProjectRequest) (*ProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteResponse, error)
	GetMyCompanyProfile(context.Context, *GetMyCompanyProfileRequest) (*CompanyProfileResponse, error)
	GetCompanyProfile(context.Context, *GetCompanyProfileRequest) (*CompanyProfileResponse, error)
	UpdateCompanyProfile(context.Context, *UpdateCompanyProfileRequest) (*CompanyProfileResponse, error)
	UploadLogo(context.Context, *UploadLogoRequest) (*UploadLogoResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) GetMyStudentProfile(context.Context, *GetMyStudentProfileRequest) (*StudentProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyStudentProfile not implemented")
}
func (UnimplementedProfileServiceServer) GetStudentProfile(context.Context, *GetStudentProfileRequest) (*StudentProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentProfile not implemented")
}
func (UnimplementedProfileServiceServer) UpdateStudentProfile(context.Context, *UpdateStudentProfileRequest) (*StudentProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStudentProfile not implemented")
}
func (UnimplementedProfileServiceServer) UploadAvatar(context.Context, *UploadAvatarRequest) (*UploadAvatarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedProfileServiceServer) UploadResume(context.Context, *UploadResumeRequest) (*UploadResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadResume not implemented")
}
func (UnimplementedProfileServiceServer) GetResumeURL(context.Context, *GetResumeURLRequest) (*GetResumeURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResumeURL not implemented")
}
func (UnimplementedProfileServiceServer) AddEducation(context.Context, *AddEducationRequest) (*EducationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEducation not implemented")
}
func (UnimplementedProfileServiceServer) UpdateEducation(context.Context, *UpdateEducationRequest) (*EducationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEducation not implemented")
}
func (UnimplementedProfileServiceServer) DeleteEducation(context.Context, *DeleteEducationRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEducation not implemented")
}
func (UnimplementedProfileServiceServer) AddExperience(context.Context, *AddExperienceRequest) (*ExperienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExperience not implemented")
}
func (UnimplementedProfileServiceServer) UpdateExperience(context.Context, *UpdateExperienceRequest) (*ExperienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExperience not implemented")
}
func (UnimplementedProfileServiceServer) DeleteExperience(context.Context, *DeleteExperienceRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExperience not implemented")
}
func (UnimplementedProfileServiceServer) AddProject(context.Context, *AddProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProject not implemented")
}
func (UnimplementedProfileServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedProfileServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProfileServiceServer) GetMyCompanyProfile(context.Context, *GetMyCompanyProfileRequest) (*CompanyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyCompanyProfile not implemented")
}
func (UnimplementedProfileServiceServer) GetCompanyProfile(context.Context, *GetCompanyProfileRequest) (*CompanyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanyProfile not implemented")
}
func (UnimplementedProfileServiceServer) UpdateCompanyProfile(context.Context, *UpdateCompanyProfileRequest) (*CompanyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompanyProfile not implemented")
}
func (UnimplementedProfileServiceServer) UploadLogo(context.Context, *UploadLogoRequest) (*UploadLogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadLogo not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_GetMyStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetMyStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetMyStudentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetMyStudentProfile(ctx, req.(*GetMyStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetStudentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetStudentProfile(ctx, req.(*GetStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateStudentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateStudentProfile(ctx, req.(*UpdateStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UploadAvatar(ctx, req.(*UploadAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UploadResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UploadResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UploadResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UploadResume(ctx, req.(*UploadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetResumeURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResumeURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetResumeURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetResumeURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetResumeURL(ctx, req.(*GetResumeURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_AddEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).AddEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_AddEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).AddEducation(ctx, req.(*AddEducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateEducation(ctx, req.(*UpdateEducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_DeleteEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteEducation(ctx, req.(*DeleteEducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_AddExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).AddExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_AddExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).AddExperience(ctx, req.(*AddExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateExperience(ctx, req.(*UpdateExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_DeleteExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteExperience(ctx, req.(*DeleteExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_AddProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).AddProject(ctx, req.(*AddProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetMyCompanyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCompanyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetMyCompanyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetMyCompanyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetMyCompanyProfile(ctx, req.(*GetMyCompanyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetCompanyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetCompanyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetCompanyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetCompanyProfile(ctx, req.(*GetCompanyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateCompanyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateCompanyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateCompanyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateCompanyProfile(ctx, req.(*UpdateCompanyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UploadLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UploadLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UploadLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UploadLogo(ctx, req.(*UploadLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyStudentProfile",
			Handler:    _ProfileService_GetMyStudentProfile_Handler,
		},
		{
			MethodName: "GetStudentProfile",
			Handler:    _ProfileService_GetStudentProfile_Handler,
		},
		{
			MethodName: "UpdateStudentProfile",
			Handler:    _ProfileService_UpdateStudentProfile_Handler,
		},
		{
			MethodName: "UploadAvatar",
			Handler:    _ProfileService_UploadAvatar_Handler,
		},
		{
			MethodName: "UploadResume",
			Handler:    _ProfileService_UploadResume_Handler,
		},
		{
			MethodName: "GetResumeURL",
			Handler:    _ProfileService_GetResumeURL_Handler,
		},
		{
			MethodName: "AddEducation",
			Handler:    _ProfileService_AddEducation_Handler,
		},
		{
			MethodName: "UpdateEducation",
			Handler:    _ProfileService_UpdateEducation_Handler,
		},
		{
			MethodName: "DeleteEducation",
			Handler:    _ProfileService_DeleteEducation_Handler,
		},
		{
			MethodName: "AddExperience",
			Handler:    _ProfileService_AddExperience_Handler,
		},
		{
			MethodName: "UpdateExperience",
			Handler:    _ProfileService_UpdateExperience_Handler,
		},
		{
			MethodName: "DeleteExperience",
			Handler:    _ProfileService_DeleteExperience_Handler,
		},
		{
			MethodName: "AddProject",
			Handler:    _ProfileService_AddProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProfileService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProfileService_DeleteProject_Handler,
		},
		{
			MethodName: "GetMyCompanyProfile",
			Handler:    _ProfileService_GetMyCompanyProfile_Handler,
		},
		{
			MethodName: "GetCompanyProfile",
			Handler:    _ProfileService_GetCompanyProfile_Handler,
		},
		{
			MethodName: "UpdateCompanyProfile",
			Handler:    _ProfileService_UpdateCompanyProfile_Handler,
		},
		{
			MethodName: "UploadLogo",
			Handler:    _ProfileService_UploadLogo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/profile/profile.proto",
}
