// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/listing/listing.proto

package listing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId     string                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Skill         string                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	IsRequired    bool                   `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingSkill) Reset() {
	*x = ListingSkill{}
	mi := &file_proto_listing_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSkill) ProtoMessage() {}

func (x *ListingSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSkill.ProtoReflect.Descriptor instead.
func (*ListingSkill) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{0}
}

func (x *ListingSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingSkill) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ListingSkill) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *ListingSkill) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type CompanyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Industry      string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyInfo) Reset() {
	*x = CompanyInfo{}
	mi := &file_proto_listing_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfo) ProtoMessage() {}

func (x *CompanyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfo.ProtoReflect.Descriptor instead.
func (*CompanyInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyInfo) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CompanyInfo) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CompanyInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type ListingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId      string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Company        *CompanyInfo           `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Requirements   string                 `protobuf:"bytes,6,opt,name=requirements,proto3" json:"requirements,omitempty"`
	WhatWeOffer    string                 `protobuf:"bytes,7,opt,name=what_we_offer,json=whatWeOffer,proto3" json:"what_we_offer,omitempty"`
	City           string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Format         string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	EmploymentType string                 `protobuf:"bytes,10,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	SalaryFrom     int64                  `protobuf:"varint,11,opt,name=salary_from,json=salaryFrom,proto3" json:"salary_from,omitempty"`
	SalaryTo       int64                  `protobuf:"varint,12,opt,name=salary_to,json=salaryTo,proto3" json:"salary_to,omitempty"`
	SalaryCurrency string                 `protobuf:"bytes,13,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Deadline       string                 `protobuf:"bytes,14,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Status         string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	Skills         []*ListingSkill        `protobuf:"bytes,16,rep,name=skills,proto3" json:"skills,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_proto_listing_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListingResponse) GetCompany() *CompanyInfo {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *ListingResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingResponse) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *ListingResponse) GetWhatWeOffer() string {
	if x != nil {
		return x.WhatWeOffer
	}
	return ""
}

func (x *ListingResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ListingResponse) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *ListingResponse) GetSalaryFrom() int64 {
	if x != nil {
		return x.SalaryFrom
	}
	return 0
}

func (x *ListingResponse) GetSalaryTo() int64 {
	if x != nil {
		return x.SalaryTo
	}
	return 0
}

func (x *ListingResponse) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *ListingResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *ListingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListingResponse) GetSkills() []*ListingSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListingResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ListingResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetListingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Format         string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	EmploymentType string                 `protobuf:"bytes,3,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	City           string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Skill          string                 `protobuf:"bytes,5,opt,name=skill,proto3" json:"skill,omitempty"`
	Page           int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	Limit          int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{3}
}

func (x *GetListingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetListingsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetListingsRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *GetListingsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetListingsRequest) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *GetListingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListingResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsResponse) Reset() {
	*x = GetListingsResponse{}
	mi := &file_proto_listing_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsResponse) ProtoMessage() {}

func (x *GetListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsResponse.ProtoReflect.Descriptor instead.
func (*GetListingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{4}
}

func (x *GetListingsResponse) GetItems() []*ListingResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetListingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetListingsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListingsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{5}
}

func (x *GetListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMyListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyListingsRequest) Reset() {
	*x = GetMyListingsRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyListingsRequest) ProtoMessage() {}

func (x *GetMyListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyListingsRequest.ProtoReflect.Descriptor instead.
func (*GetMyListingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyListingsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetMyListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListingResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyListingsResponse) Reset() {
	*x = GetMyListingsResponse{}
	mi := &file_proto_listing_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyListingsResponse) ProtoMessage() {}

func (x *GetMyListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyListingsResponse.ProtoReflect.Descriptor instead.
func (*GetMyListingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{7}
}

func (x *GetMyListingsResponse) GetItems() []*ListingResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateListingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompanyId      string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Requirements   string                 `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	WhatWeOffer    string                 `protobuf:"bytes,5,opt,name=what_we_offer,json=whatWeOffer,proto3" json:"what_we_offer,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Format         string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	EmploymentType string                 `protobuf:"bytes,8,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	SalaryFrom     int64                  `protobuf:"varint,9,opt,name=salary_from,json=salaryFrom,proto3" json:"salary_from,omitempty"`
	SalaryTo       int64                  `protobuf:"varint,10,opt,name=salary_to,json=salaryTo,proto3" json:"salary_to,omitempty"`
	SalaryCurrency string                 `protobuf:"bytes,11,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Deadline       string                 `protobuf:"bytes,12,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{8}
}

func (x *CreateListingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *CreateListingRequest) GetWhatWeOffer() string {
	if x != nil {
		return x.WhatWeOffer
	}
	return ""
}

func (x *CreateListingRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateListingRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateListingRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *CreateListingRequest) GetSalaryFrom() int64 {
	if x != nil {
		return x.SalaryFrom
	}
	return 0
}

func (x *CreateListingRequest) GetSalaryTo() int64 {
	if x != nil {
		return x.SalaryTo
	}
	return 0
}

func (x *CreateListingRequest) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *CreateListingRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type UpdateListingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId      string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Requirements   string                 `protobuf:"bytes,5,opt,name=requirements,proto3" json:"requirements,omitempty"`
	WhatWeOffer    string                 `protobuf:"bytes,6,opt,name=what_we_offer,json=whatWeOffer,proto3" json:"what_we_offer,omitempty"`
	City           string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Format         string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`
	EmploymentType string                 `protobuf:"bytes,9,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	SalaryFrom     int64                  `protobuf:"varint,10,opt,name=salary_from,json=salaryFrom,proto3" json:"salary_from,omitempty"`
	SalaryTo       int64                  `protobuf:"varint,11,opt,name=salary_to,json=salaryTo,proto3" json:"salary_to,omitempty"`
	SalaryCurrency string                 `protobuf:"bytes,12,opt,name=salary_currency,json=salaryCurrency,proto3" json:"salary_currency,omitempty"`
	Deadline       string                 `protobuf:"bytes,13,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateListingRequest) Reset() {
	*x = UpdateListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingRequest) ProtoMessage() {}

func (x *UpdateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateListingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateListingRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *UpdateListingRequest) GetWhatWeOffer() string {
	if x != nil {
		return x.WhatWeOffer
	}
	return ""
}

func (x *UpdateListingRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateListingRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UpdateListingRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *UpdateListingRequest) GetSalaryFrom() int64 {
	if x != nil {
		return x.SalaryFrom
	}
	return 0
}

func (x *UpdateListingRequest) GetSalaryTo() int64 {
	if x != nil {
		return x.SalaryTo
	}
	return 0
}

func (x *UpdateListingRequest) GetSalaryCurrency() string {
	if x != nil {
		return x.SalaryCurrency
	}
	return ""
}

func (x *UpdateListingRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteListingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type DeleteListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingResponse) Reset() {
	*x = DeleteListingResponse{}
	mi := &file_proto_listing_listing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingResponse) ProtoMessage() {}

func (x *DeleteListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingResponse.ProtoReflect.Descriptor instead.
func (*DeleteListingResponse) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteListingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishListingRequest) Reset() {
	*x = PublishListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishListingRequest) ProtoMessage() {}

func (x *PublishListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishListingRequest.ProtoReflect.Descriptor instead.
func (*PublishListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{12}
}

func (x *PublishListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishListingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type CloseListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseListingRequest) Reset() {
	*x = CloseListingRequest{}
	mi := &file_proto_listing_listing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseListingRequest) ProtoMessage() {}

func (x *CloseListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_listing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseListingRequest.ProtoReflect.Descriptor instead.
func (*CloseListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_listing_proto_rawDescGZIP(), []int{13}
}

func (x *CloseListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloseListingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_proto_listing_listing_proto protoreflect.FileDescriptor

const file_proto_listing_listing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/listing/listing.proto\x12\alisting\"t\n" +
	"\fListingSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\tR\tlistingId\x12\x14\n" +
	"\x05skill\x18\x03 \x01(\tR\x05skill\x12\x1f\n" +
	"\vis_required\x18\x04 \x01(\bR\n" +
	"isRequired\"|\n" +
	"\vCompanyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\"\xcd\x04\n" +
	"\x0fListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12.\n" +
	"\acompany\x18\x03 \x01(\v2\x14.listing.CompanyInfoR\acompany\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x06 \x01(\tR\frequirements\x12\"\n" +
	"\rwhat_we_offer\x18\a \x01(\tR\vwhatWeOffer\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\x12'\n" +
	"\x0femployment_type\x18\n" +
	" \x01(\tR\x0eemploymentType\x12\x1f\n" +
	"\vsalary_from\x18\v \x01(\x03R\n" +
	"salaryFrom\x12\x1b\n" +
	"\tsalary_to\x18\f \x01(\x03R\bsalaryTo\x12'\n" +
	"\x0fsalary_currency\x18\r \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\bdeadline\x18\x0e \x01(\tR\bdeadline\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12-\n" +
	"\x06skills\x18\x10 \x03(\v2\x15.listing.ListingSkillR\x06skills\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt\"\xbf\x01\n" +
	"\x12GetListingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12'\n" +
	"\x0femployment_type\x18\x03 \x01(\tR\x0eemploymentType\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05skill\x18\x05 \x01(\tR\x05skill\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"\x85\x01\n" +
	"\x13GetListingsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.listing.ListingResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x14GetMyListingsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"G\n" +
	"\x15GetMyListingsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.listing.ListingResponseR\x05items\"\x8d\x03\n" +
	"\x14CreateListingRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x04 \x01(\tR\frequirements\x12\"\n" +
	"\rwhat_we_offer\x18\x05 \x01(\tR\vwhatWeOffer\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12'\n" +
	"\x0femployment_type\x18\b \x01(\tR\x0eemploymentType\x12\x1f\n" +
	"\vsalary_from\x18\t \x01(\x03R\n" +
	"salaryFrom\x12\x1b\n" +
	"\tsalary_to\x18\n" +
	" \x01(\x03R\bsalaryTo\x12'\n" +
	"\x0fsalary_currency\x18\v \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\bdeadline\x18\f \x01(\tR\bdeadline\"\x9d\x03\n" +
	"\x14UpdateListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x05 \x01(\tR\frequirements\x12\"\n" +
	"\rwhat_we_offer\x18\x06 \x01(\tR\vwhatWeOffer\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06format\x12'\n" +
	"\x0femployment_type\x18\t \x01(\tR\x0eemploymentType\x12\x1f\n" +
	"\vsalary_from\x18\n" +
	" \x01(\x03R\n" +
	"salaryFrom\x12\x1b\n" +
	"\tsalary_to\x18\v \x01(\x03R\bsalaryTo\x12'\n" +
	"\x0fsalary_currency\x18\f \x01(\tR\x0esalaryCurrency\x12\x1a\n" +
	"\bdeadline\x18\r \x01(\tR\bdeadline\"E\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"1\n" +
	"\x15DeleteListingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x15PublishListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"D\n" +
	"\x13CloseListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId2\xe6\x04\n" +
	"\x0eListingService\x12H\n" +
	"\vGetListings\x12\x1b.listing.GetListingsRequest\x1a\x1c.listing.GetListingsResponse\x12B\n" +
	"\n" +
	"GetListing\x12\x1a.listing.GetListingRequest\x1a\x18.listing.ListingResponse\x12N\n" +
	"\rGetMyListings\x12\x1d.listing.GetMyListingsRequest\x1a\x1e.listing.GetMyListingsResponse\x12H\n" +
	"\rCreateListing\x12\x1d.listing.CreateListingRequest\x1a\x18.listing.ListingResponse\x12H\n" +
	"\rUpdateListing\x12\x1d.listing.UpdateListingRequest\x1a\x18.listing.ListingResponse\x12N\n" +
	"\rDeleteListing\x12\x1d.listing.DeleteListingRequest\x1a\x1e.listing.DeleteListingResponse\x12J\n" +
	"\x0ePublishListing\x12\x1e.listing.PublishListingRequest\x1a\x18.listing.ListingResponse\x12F\n" +
	"\fCloseListing\x12\x1c.listing.CloseListingRequest\x1a\x18.listing.ListingResponseB4Z2github.com/Kost0/internship-exchange/proto/listingb\x06proto3"

var (
	file_proto_listing_listing_proto_rawDescOnce sync.Once
	file_proto_listing_listing_proto_rawDescData []byte
)

func file_proto_listing_listing_proto_rawDescGZIP() []byte {
	file_proto_listing_listing_proto_rawDescOnce.Do(func() {
		file_proto_listing_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_listing_listing_proto_rawDesc), len(file_proto_listing_listing_proto_rawDesc)))
	})
	return file_proto_listing_listing_proto_rawDescData
}

var file_proto_listing_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_listing_listing_proto_goTypes = []any{
	(*ListingSkill)(nil),          // 0: listing.ListingSkill
	(*CompanyInfo)(nil),           // 1: listing.CompanyInfo
	(*ListingResponse)(nil),       // 2: listing.ListingResponse
	(*GetListingsRequest)(nil),    // 3: listing.GetListingsRequest
	(*GetListingsResponse)(nil),   // 4: listing.GetListingsResponse
	(*GetListingRequest)(nil),     // 5: listing.GetListingRequest
	(*GetMyListingsRequest)(nil),  // 6: listing.GetMyListingsRequest
	(*GetMyListingsResponse)(nil), // 7: listing.GetMyListingsResponse
	(*CreateListingRequest)(nil),  // 8: listing.CreateListingRequest
	(*UpdateListingRequest)(nil),  // 9: listing.UpdateListingRequest
	(*DeleteListingRequest)(nil),  // 10: listing.DeleteListingRequest
	(*DeleteListingResponse)(nil), // 11: listing.DeleteListingResponse
	(*PublishListingRequest)(nil), // 12: listing.PublishListingRequest
	(*CloseListingRequest)(nil),   // 13: listing.CloseListingRequest
}
var file_proto_listing_listing_proto_depIdxs = []int32{
	1,  // 0: listing.ListingResponse.company:type_name -> listing.CompanyInfo
	0,  // 1: listing.ListingResponse.skills:type_name -> listing.ListingSkill
	2,  // 2: listing.GetListingsResponse.items:type_name -> listing.ListingResponse
	2,  // 3: listing.GetMyListingsResponse.items:type_name -> listing.ListingResponse
	3,  // 4: listing.ListingService.GetListings:input_type -> listing.GetListingsRequest
	5,  // 5: listing.ListingService.GetListing:input_type -> listing.GetListingRequest
	6,  // 6: listing.ListingService.GetMyListings:input_type -> listing.GetMyListingsRequest
	8,  // 7: listing.ListingService.CreateListing:input_type -> listing.CreateListingRequest
	9,  // 8: listing.ListingService.UpdateListing:input_type -> listing.UpdateListingRequest
	10, // 9: listing.ListingService.DeleteListing:input_type -> listing.DeleteListingRequest
	12, // 10: listing.ListingService.PublishListing:input_type -> listing.PublishListingRequest
	13, // 11: listing.ListingService.CloseListing:input_type -> listing.CloseListingRequest
	4,  // 12: listing.ListingService.GetListings:output_type -> listing.GetListingsResponse
	2,  // 13: listing.ListingService.GetListing:output_type -> listing.ListingResponse
	7,  // 14: listing.ListingService.GetMyListings:output_type -> listing.GetMyListingsResponse
	2,  // 15: listing.ListingService.CreateListing:output_type -> listing.ListingResponse
	2,  // 16: listing.ListingService.UpdateListing:output_type -> listing.ListingResponse
	11, // 17: listing.ListingService.DeleteListing:output_type -> listing.DeleteListingResponse
	2,  // 18: listing.ListingService.PublishListing:output_type -> listing.ListingResponse
	2,  // 19: listing.ListingService.CloseListing:output_type -> listing.ListingResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_listing_listing_proto_init() }
func file_proto_listing_listing_proto_init() {
	if File_proto_listing_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_listing_listing_proto_rawDesc), len(file_proto_listing_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_listing_listing_proto_goTypes,
		DependencyIndexes: file_proto_listing_listing_proto_depIdxs,
		MessageInfos:      file_proto_listing_listing_proto_msgTypes,
	}.Build()
	File_proto_listing_listing_proto = out.File
	file_proto_listing_listing_proto_goTypes = nil
	file_proto_listing_listing_proto_depIdxs = nil
}
