// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/listing/listing.proto

package listing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListingService_GetListings_FullMethodName    = "/listing.ListingService/GetListings"
	ListingService_GetListing_FullMethodName     = "/listing.ListingService/GetListing"
	ListingService_GetMyListings_FullMethodName  = "/listing.ListingService/GetMyListings"
	ListingService_CreateListing_FullMethodName  = "/listing.ListingService/CreateListing"
	ListingService_UpdateListing_FullMethodName  = "/listing.ListingService/UpdateListing"
	ListingService_DeleteListing_FullMethodName  = "/listing.ListingService/DeleteListing"
	ListingService_PublishListing_FullMethodName = "/listing.ListingService/PublishListing"
	ListingService_CloseListing_FullMethodName   = "/listing.ListingService/CloseListing"
)

// ListingServiceClient is the client API for ListingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListingServiceClient interface {
	GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error)
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	GetMyListings(ctx context.Context, in *GetMyListingsRequest, opts ...grpc.CallOption) (*GetMyListingsResponse, error)
	CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error)
	PublishListing(ctx context.Context, in *PublishListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	CloseListing(ctx context.Context, in *CloseListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
}

type listingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListingServiceClient(cc grpc.ClientConnInterface) ListingServiceClient {
	return &listingServiceClient{cc}
}

func (c *listingServiceClient) GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingsResponse)
	err := c.cc.Invoke(ctx, ListingService_GetListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, ListingService_GetListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) GetMyListings(ctx context.Context, in *GetMyListingsRequest, opts ...grpc.CallOption) (*GetMyListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyListingsResponse)
	err := c.cc.Invoke(ctx, ListingService_GetMyListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, ListingService_CreateListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, ListingService_UpdateListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*DeleteListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteListingResponse)
	err := c.cc.Invoke(ctx, ListingService_DeleteListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) PublishListing(ctx context.Context, in *PublishListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, ListingService_PublishListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) CloseListing(ctx context.Context, in *CloseListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, ListingService_CloseListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListingServiceServer is the server API for ListingService service.
// All implementations must embed UnimplementedListingServiceServer
// for forward compatibility.
type ListingServiceServer interface {
	GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error)
	GetListing(context.Context, *GetListingRequest) (*ListingResponse, error)
	GetMyListings(context.Context, *GetMyListingsRequest) (*GetMyListingsResponse, error)
	CreateListing(context.Context, *CreateListingRequest) (*ListingResponse, error)
	UpdateListing(context.Context, *UpdateListingRequest) (*ListingResponse, error)
	DeleteListing(context.Context, *DeleteListingRequest) (*DeleteListingResponse, error)
	PublishListing(context.Context, *PublishListingRequest) (*ListingResponse, error)
	CloseListing(context.Context, *CloseListingRequest) (*ListingResponse, error)
	mustEmbedUnimplementedListingServiceServer()
}

// UnimplementedListingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListingServiceServer struct{}

func (UnimplementedListingServiceServer) GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListings not implemented")
}
func (UnimplementedListingServiceServer) GetListing(context.Context, *GetListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListing not implemented")
}
func (UnimplementedListingServiceServer) GetMyListings(context.Context, *GetMyListingsRequest) (*GetMyListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyListings not implemented")
}
func (UnimplementedListingServiceServer) CreateListing(context.Context, *CreateListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListing not implemented")
}
func (UnimplementedListingServiceServer) UpdateListing(context.Context, *UpdateListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateListing not implemented")
}
func (UnimplementedListingServiceServer) DeleteListing(context.Context, *DeleteListingRequest) (*DeleteListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteListing not implemented")
}
func (UnimplementedListingServiceServer) PublishListing(context.Context, *PublishListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishListing not implemented")
}
func (UnimplementedListingServiceServer) CloseListing(context.Context, *CloseListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseListing not implemented")
}
func (UnimplementedListingServiceServer) mustEmbedUnimplementedListingServiceServer() {}
func (UnimplementedListingServiceServer) testEmbeddedByValue()                        {}

// UnsafeListingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListingServiceServer will
// result in compilation errors.
type UnsafeListingServiceServer interface {
	mustEmbedUnimplementedListingServiceServer()
}

func RegisterListingServiceServer(s grpc.ServiceRegistrar, srv ListingServiceServer) {
	// If the following call panics, it indicates UnimplementedListingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListingService_ServiceDesc, srv)
}

func _ListingService_GetListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_GetListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListings(ctx, req.(*GetListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_GetListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_GetMyListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetMyListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_GetMyListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetMyListings(ctx, req.(*GetMyListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_CreateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).CreateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_CreateListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).CreateListing(ctx, req.(*CreateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_UpdateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).UpdateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_UpdateListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).UpdateListing(ctx, req.(*UpdateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_DeleteListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).DeleteListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_DeleteListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).DeleteListing(ctx, req.(*DeleteListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_PublishListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).PublishListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_PublishListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).PublishListing(ctx, req.(*PublishListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_CloseListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).CloseListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_CloseListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).CloseListing(ctx, req.(*CloseListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListingService_ServiceDesc is the grpc.ServiceDesc for ListingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listing.ListingService",
	HandlerType: (*ListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListings",
			Handler:    _ListingService_GetListings_Handler,
		},
		{
			MethodName: "GetListing",
			Handler:    _ListingService_GetListing_Handler,
		},
		{
			MethodName: "GetMyListings",
			Handler:    _ListingService_GetMyListings_Handler,
		},
		{
			MethodName: "CreateListing",
			Handler:    _ListingService_CreateListing_Handler,
		},
		{
			MethodName: "UpdateListing",
			Handler:    _ListingService_UpdateListing_Handler,
		},
		{
			MethodName: "DeleteListing",
			Handler:    _ListingService_DeleteListing_Handler,
		},
		{
			MethodName: "PublishListing",
			Handler:    _ListingService_PublishListing_Handler,
		},
		{
			MethodName: "CloseListing",
			Handler:    _ListingService_CloseListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/listing/listing.proto",
}
