// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/application/application.proto

package application

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	OldStatus     string                 `protobuf:"bytes,3,opt,name=old_status,json=oldStatus,proto3" json:"old_status,omitempty"`
	NewStatus     string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	ChangedAt     string                 `protobuf:"bytes,6,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationEvent) Reset() {
	*x = ApplicationEvent{}
	mi := &file_proto_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationEvent) ProtoMessage() {}

func (x *ApplicationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationEvent.ProtoReflect.Descriptor instead.
func (*ApplicationEvent) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationEvent) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationEvent) GetOldStatus() string {
	if x != nil {
		return x.OldStatus
	}
	return ""
}

func (x *ApplicationEvent) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *ApplicationEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ApplicationEvent) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ResumeUrl     string                 `protobuf:"bytes,6,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_proto_application_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{1}
}

func (x *StudentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StudentInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *StudentInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StudentInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *StudentInfo) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

type ListingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,4,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingInfo) Reset() {
	*x = ListingInfo{}
	mi := &file_proto_application_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingInfo) ProtoMessage() {}

func (x *ListingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingInfo.ProtoReflect.Descriptor instead.
func (*ListingInfo) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{2}
}

func (x *ListingInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingInfo) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListingInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type ApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,3,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	CoverLetter   string                 `protobuf:"bytes,4,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Student       *StudentInfo           `protobuf:"bytes,8,opt,name=student,proto3" json:"student,omitempty"`
	Listing       *ListingInfo           `protobuf:"bytes,9,opt,name=listing,proto3" json:"listing,omitempty"`
	Events        []*ApplicationEvent    `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationResponse) Reset() {
	*x = ApplicationResponse{}
	mi := &file_proto_application_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationResponse) ProtoMessage() {}

func (x *ApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationResponse.ProtoReflect.Descriptor instead.
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ApplicationResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ApplicationResponse) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ApplicationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplicationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApplicationResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ApplicationResponse) GetStudent() *StudentInfo {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ApplicationResponse) GetListing() *ListingInfo {
	if x != nil {
		return x.Listing
	}
	return nil
}

func (x *ApplicationResponse) GetEvents() []*ApplicationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	CoverLetter   string                 `protobuf:"bytes,3,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	StudentEmail  string                 `protobuf:"bytes,4,opt,name=student_email,json=studentEmail,proto3" json:"student_email,omitempty"`
	CompanyEmail  string                 `protobuf:"bytes,5,opt,name=company_email,json=companyEmail,proto3" json:"company_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_proto_application_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ApplyRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ApplyRequest) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ApplyRequest) GetStudentEmail() string {
	if x != nil {
		return x.StudentEmail
	}
	return ""
}

func (x *ApplyRequest) GetCompanyEmail() string {
	if x != nil {
		return x.CompanyEmail
	}
	return ""
}

type GetMyApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationsRequest) Reset() {
	*x = GetMyApplicationsRequest{}
	mi := &file_proto_application_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationsRequest) ProtoMessage() {}

func (x *GetMyApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetMyApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyApplicationsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ApplicationResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsResponse) Reset() {
	*x = GetApplicationsResponse{}
	mi := &file_proto_application_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsResponse) ProtoMessage() {}

func (x *GetApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{6}
}

func (x *GetApplicationsResponse) GetItems() []*ApplicationResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_proto_application_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_proto_application_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetListingApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingApplicationsRequest) Reset() {
	*x = GetListingApplicationsRequest{}
	mi := &file_proto_application_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingApplicationsRequest) ProtoMessage() {}

func (x *GetListingApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetListingApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{9}
}

func (x *GetListingApplicationsRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *GetListingApplicationsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ChangeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusRequest) Reset() {
	*x = ChangeStatusRequest{}
	mi := &file_proto_application_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusRequest) ProtoMessage() {}

func (x *ChangeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeStatusRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ChangeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChangeStatusRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_application_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetHistoryRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ApplicationEvent    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_application_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{12}
}

func (x *GetHistoryResponse) GetEvents() []*ApplicationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_application_application_proto protoreflect.FileDescriptor

const file_proto_application_application_proto_rawDesc = "" +
	"\n" +
	"#proto/application/application.proto\x12\vapplication\"\xc0\x01\n" +
	"\x10ApplicationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"old_status\x18\x03 \x01(\tR\toldStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tR\tnewStatus\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x06 \x01(\tR\tchangedAt\"\xab\x01\n" +
	"\vStudentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"resume_url\x18\x06 \x01(\tR\tresumeUrl\"u\n" +
	"\vListingInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12!\n" +
	"\fcompany_name\x18\x04 \x01(\tR\vcompanyName\"\xfb\x02\n" +
	"\x13ApplicationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\tR\tlistingId\x12!\n" +
	"\fcover_letter\x18\x04 \x01(\tR\vcoverLetter\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x122\n" +
	"\astudent\x18\b \x01(\v2\x18.application.StudentInfoR\astudent\x122\n" +
	"\alisting\x18\t \x01(\v2\x18.application.ListingInfoR\alisting\x125\n" +
	"\x06events\x18\n" +
	" \x03(\v2\x1d.application.ApplicationEventR\x06events\"\xb9\x01\n" +
	"\fApplyRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\tR\tlistingId\x12!\n" +
	"\fcover_letter\x18\x03 \x01(\tR\vcoverLetter\x12#\n" +
	"\rstudent_email\x18\x04 \x01(\tR\fstudentEmail\x12#\n" +
	"\rcompany_email\x18\x05 \x01(\tR\fcompanyEmail\"9\n" +
	"\x18GetMyApplicationsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"Q\n" +
	"\x17GetApplicationsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .application.ApplicationResponseR\x05items\"@\n" +
	"\x0fWithdrawRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\",\n" +
	"\x10WithdrawResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\x1dGetListingApplicationsRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"v\n" +
	"\x13ChangeStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"B\n" +
	"\x11GetHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"K\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.application.ApplicationEventR\x06events2\x94\x04\n" +
	"\x12ApplicationService\x12D\n" +
	"\x05Apply\x12\x19.application.ApplyRequest\x1a .application.ApplicationResponse\x12`\n" +
	"\x11GetMyApplications\x12%.application.GetMyApplicationsRequest\x1a$.application.GetApplicationsResponse\x12G\n" +
	"\bWithdraw\x12\x1c.application.WithdrawRequest\x1a\x1d.application.WithdrawResponse\x12j\n" +
	"\x16GetListingApplications\x12*.application.GetListingApplicationsRequest\x1a$.application.GetApplicationsResponse\x12R\n" +
	"\fChangeStatus\x12 .application.ChangeStatusRequest\x1a .application.ApplicationResponse\x12M\n" +
	"\n" +
	"GetHistory\x12\x1e.application.GetHistoryRequest\x1a\x1f.application.GetHistoryResponseB8Z6github.com/Kost0/internship-exchange/proto/applicationb\x06proto3"

var (
	file_proto_application_application_proto_rawDescOnce sync.Once
	file_proto_application_application_proto_rawDescData []byte
)

func file_proto_application_application_proto_rawDescGZIP() []byte {
	file_proto_application_application_proto_rawDescOnce.Do(func() {
		file_proto_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)))
	})
	return file_proto_application_application_proto_rawDescData
}

var file_proto_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_application_application_proto_goTypes = []any{
	(*ApplicationEvent)(nil),              // 0: application.ApplicationEvent
	(*StudentInfo)(nil),                   // 1: application.StudentInfo
	(*ListingInfo)(nil),                   // 2: application.ListingInfo
	(*ApplicationResponse)(nil),           // 3: application.ApplicationResponse
	(*ApplyRequest)(nil),                  // 4: application.ApplyRequest
	(*GetMyApplicationsRequest)(nil),      // 5: application.GetMyApplicationsRequest
	(*GetApplicationsResponse)(nil),       // 6: application.GetApplicationsResponse
	(*WithdrawRequest)(nil),               // 7: application.WithdrawRequest
	(*WithdrawResponse)(nil),              // 8: application.WithdrawResponse
	(*GetListingApplicationsRequest)(nil), // 9: application.GetListingApplicationsRequest
	(*ChangeStatusRequest)(nil),           // 10: application.ChangeStatusRequest
	(*GetHistoryRequest)(nil),             // 11: application.GetHistoryRequest
	(*GetHistoryResponse)(nil),            // 12: application.GetHistoryResponse
}
var file_proto_application_application_proto_depIdxs = []int32{
	1,  // 0: application.ApplicationResponse.student:type_name -> application.StudentInfo
	2,  // 1: application.ApplicationResponse.listing:type_name -> application.ListingInfo
	0,  // 2: application.ApplicationResponse.events:type_name -> application.ApplicationEvent
	3,  // 3: application.GetApplicationsResponse.items:type_name -> application.ApplicationResponse
	0,  // 4: application.GetHistoryResponse.events:type_name -> application.ApplicationEvent
	4,  // 5: application.ApplicationService.Apply:input_type -> application.ApplyRequest
	5,  // 6: application.ApplicationService.GetMyApplications:input_type -> application.GetMyApplicationsRequest
	7,  // 7: application.ApplicationService.Withdraw:input_type -> application.WithdrawRequest
	9,  // 8: application.ApplicationService.GetListingApplications:input_type -> application.GetListingApplicationsRequest
	10, // 9: application.ApplicationService.ChangeStatus:input_type -> application.ChangeStatusRequest
	11, // 10: application.ApplicationService.GetHistory:input_type -> application.GetHistoryRequest
	3,  // 11: application.ApplicationService.Apply:output_type -> application.ApplicationResponse
	6,  // 12: application.ApplicationService.GetMyApplications:output_type -> application.GetApplicationsResponse
	8,  // 13: application.ApplicationService.Withdraw:output_type -> application.WithdrawResponse
	6,  // 14: application.ApplicationService.GetListingApplications:output_type -> application.GetApplicationsResponse
	3,  // 15: application.ApplicationService.ChangeStatus:output_type -> application.ApplicationResponse
	12, // 16: application.ApplicationService.GetHistory:output_type -> application.GetHistoryResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_application_application_proto_init() }
func file_proto_application_application_proto_init() {
	if File_proto_application_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_application_application_proto_goTypes,
		DependencyIndexes: file_proto_application_application_proto_depIdxs,
		MessageInfos:      file_proto_application_application_proto_msgTypes,
	}.Build()
	File_proto_application_application_proto = out.File
	file_proto_application_application_proto_goTypes = nil
	file_proto_application_application_proto_depIdxs = nil
}
